#! /bin/bash -e

#docker run -e BUILDKITE_AGENT_TOKEN="b2e64a3af8cf6e6fa0df3d6b803ed84f572a96f3c0500020f0" buildkite/agent

docker run -d -t --name myob-rest-api-agent buildkite/agent:3 start --token "<b2e64a3af8cf6e6fa0df3d6b803ed84f572a96f3c0500020f0>"

export STACK=myob-rest-api

docker volume create --name=myob-rest-api-vol