#!/usr/bin/env bash

set -ex

echo "-- Building --"
docker build -t myob-rest-api -f ./docker/Dockerfile .
docker run -e BUILDKITE_AGENT_TOKEN="b2e64a3af8cf6e6fa0df3d6b803ed84f572a96f3c0500020f0" buildkite/agent
echo 'done building!'