#!/usr/bin/env bash
set -eux

docker run -it \
  -v "$HOME/buildkite-agent.cfg:/buildkite/buildkite-agent.cfg:ro" \
  buildkite/agent:3

#docker run -e BUILDKITE_AGENT_TOKEN="b2e64a3af8cf6e6fa0df3d6b803ed84f572a96f3c0500020f0" buildkite/agent